### ISSUE TITLE
乃说的bug修复了么？

### ISSUE THREAD

**Issue by Provissy** [dsh0416/KanColleJ#3]
http://provissy.com/discuss/
为了配合您我写了一个抓包工具，基于Fiddler，可以方便的提取出cookie（cookie名改成了jngf）

**Comment by kinosang** [comment]
@Provissy 就是不知道 @dsh0416 是否接受被移植到 mono 平臺的 pull
另 Kinosang/KanColleJ Release 0.3 可用

**Comment by Provissy** [comment]
@kinosang 好的我的网页已更新，mono应该能直接用吧？

**Comment by Provissy** [comment]
这个工具是.net 2.0 winform么？

**Comment by kinosang** [comment]
@Provissy 0.3 是net2.0
